"npm" = [
  "@openzeppelin/contracts",
  "@openzeppelin/contracts-upgradeable",
  "@uniswap/universal-router",
  "@uniswap/v2-core",
  "@uniswap/v2-periphery",
  "@uniswap/swap-router-contracts",
  "@uniswap/v3-core",
  "@uniswap/v3-periphery",
  # "solmate",
  "@prb/math",
  "@prb/contracts",
  "@prb/proxy",
  "@prb/test",
  "@gelatonetwork/relay-context",
  "@axelar-network/axelar-cgp-solidity",
  "@axelar-network/axelar-gmp-sdk-solidity",
  "@axelar-network/interchain-token-service",
  "solady",
  "@gnosis.pm/safe-contracts",
  "@synapsecns/contracts-core",
  "@0x/contracts-zero-ex",
  "@0x/contracts-erc20",
  "@0x/contracts-utils",
  "@layerzerolabs/lz-evm-oapp-v2",
  "@eth-optimism/contracts-bedrock",
  "@solidstate/contracts",
  "erc721a",
  "@pythnetwork/pyth-sdk-solidity",
  "@redstone-finance/evm-connector",
  "@gearbox-protocol/core-v3",
  "@gearbox-protocol/integrations-v3",
  "@gearbox-protocol/core-v2",
  "@gearbox-protocol/integrations-v2",
  "@gearbox-protocol/periphery-v3",
  "dn404",
  "multicaller",
  "soledge",
  "@layerzerolabs/test-devtools-evm-foundry",
  "@tokenysolutions/t-rex",
  "@onchain-id/solidity",
  "@stargatefinance/stg-evm-v2",
  # "@chainlink/contracts",
  "@pancakeswap/v3-periphery",
  "@pancakeswap/v3-core",
  "@layerzerolabs/oapp-evm-upgradeable",
  "@layerzerolabs/lz-evm-messagelib-v2",
  "@layerzerolabs/lz-evm-protocol-v2",
  "@layerzerolabs/lz-evm-v1-0.7",
  "@layerzerolabs/oapp-evm",
  "@layerzerolabs/oft-evm",
  "@layerzerolabs/oft-evm-upgradeable",
  "@layerzerolabs/oft-alt-evm",
  "@latticexyz/store",
  "@layerzerolabs/onft-evm",
  "@solarity/solidity-lib",
]

"github" = [
  "hashgraph/hedera-forking",
  "morpho-org/morpho-blue",
  "euler-xyz/euler-interfaces",
  "crytic/properties",
  "Layr-Labs/eigenlayer-contracts",
  "Uniswap/smart-order-router",
  "openzeppelin/uniswap-hooks",
  "smartcontractkit/chainlink-evm",
  "foundry-rs/forge-std",
  "safe-global/safe-smart-account",
  "risc0/risc0-ethereum",
  "alchemyplatform/modular-account",
  "morpho-org/metamorpho-v1.1",
  "pendle-finance/pendle-core-v2-public",
  "Uniswap/v4-periphery",
  "eth-infinitism/account-abstraction",
  "worldcoin/world-id-contracts",
  "morpho-org/morpho-blue-oracles",
  "circlefin/evm-cctp-contracts",
  "morpho-org/public-allocator",
  "Uniswap/v4-core",
  "succinctlabs/sp1-contracts",
  "gnosisguild/zodiac",
  "Recon-Fuzz/setup-helpers",
  "transmissions11/solmate",
  "base-org/webauthn-sol",
  "euler-xyz/ethereum-vault-connector",
  "Cyfrin/foundry-devops",
  "gnsps/solidity-bytes-utils",
  "a16z/halmos-cheatcodes",
  "limitbreakinc/creator-token-standards",
  "Balmy-protocol/uniswap-v3-oracle",
  "smartcontractkit/chainlink-brownie-contracts",
  "Recon-Fuzz/chimera",
  "zeframlou/create3-factory",
  "smartcontractkit/ccip",
  "ava-labs/avalanche-interchain-token-transfer",
  "manifoldxyz/creator-core-solidity",
  "colinnielsen/safe-tools",
  "huff-language/foundry-huff",
  "estarriolvetch/erc721psi",
  "Cyfrin/foundry-era-contracts",
  "erc6551/reference",
  "solv-finance/erc-3525",
  "ProjectOpenSea/operator-filter-registry",
  "manifoldxyz/libraries-solidity",
  "boringcrypto/BoringSolidity",
  "0xsequence/sstore2",
  # "Uniswap/permit2",
  # "huff-language/huffmate",
]
  